### ISSUE TITLE
[Roadmap] API generation improvements

### ISSUE THREAD

**Issue by mootari** [BabylonJS/OldDocumentationSite#781]
Meta issue to track problems with and feature requests for the current API docs.  

**Note:** If you want something added to this list please create a new issue and include a reference to #781.

- [x] API builder parses union types incorrectly, adds members and parameters for additional types #712
- [x] Implement typedoc as replacement for current API builder #713
- [x] Documentation cannot currently handle one line comments #775 
- [x] Documentation currently doesn't understand getters #776
- [x] Trying to include a code sample in a document gets it turned into a link #777
- [x] Function parameters that take multiple types do not document correctly #778

**Comment by deltakosh** [comment]
Great idea
